// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/app/services/repository.go
//
// Generated by this command:
//
//	mockgen -source=./internal/app/services/repository.go -destination=./internal/app/services/mocks/mock_rep.go
//

// Package mock_services is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/stlesnik/url_shortener/internal/app/models"
	repository "github.com/stlesnik/url_shortener/internal/app/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockStorager is a mock of Storager interface.
type MockStorager struct {
	ctrl     *gomock.Controller
	recorder *MockStoragerMockRecorder
	isgomock struct{}
}

// MockStoragerMockRecorder is the mock recorder for MockStorager.
type MockStoragerMockRecorder struct {
	mock *MockStorager
}

// NewMockStorager creates a new mock instance.
func NewMockStorager(ctrl *gomock.Controller) *MockStorager {
	mock := &MockStorager{ctrl: ctrl}
	mock.recorder = &MockStoragerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorager) EXPECT() *MockStoragerMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockStorager) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockStoragerMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockStorager)(nil).Close))
}

// GetURL mocks base method.
func (m *MockStorager) GetURL(ctx context.Context, shortURL string) (models.GetURLDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetURL", ctx, shortURL)
	ret0, _ := ret[0].(models.GetURLDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetURL indicates an expected call of GetURL.
func (mr *MockStoragerMockRecorder) GetURL(ctx, shortURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetURL", reflect.TypeOf((*MockStorager)(nil).GetURL), ctx, shortURL)
}

// Ping mocks base method.
func (m *MockStorager) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockStoragerMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockStorager)(nil).Ping), ctx)
}

// SaveURL mocks base method.
func (m *MockStorager) SaveURL(ctx context.Context, shortURL, longURLStr, userID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveURL", ctx, shortURL, longURLStr, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveURL indicates an expected call of SaveURL.
func (mr *MockStoragerMockRecorder) SaveURL(ctx, shortURL, longURLStr, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveURL", reflect.TypeOf((*MockStorager)(nil).SaveURL), ctx, shortURL, longURLStr, userID)
}

// MockDBStorager is a mock of DBStorager interface.
type MockDBStorager struct {
	ctrl     *gomock.Controller
	recorder *MockDBStoragerMockRecorder
	isgomock struct{}
}

// MockDBStoragerMockRecorder is the mock recorder for MockDBStorager.
type MockDBStoragerMockRecorder struct {
	mock *MockDBStorager
}

// NewMockDBStorager creates a new mock instance.
func NewMockDBStorager(ctrl *gomock.Controller) *MockDBStorager {
	mock := &MockDBStorager{ctrl: ctrl}
	mock.recorder = &MockDBStoragerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDBStorager) EXPECT() *MockDBStoragerMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockDBStorager) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockDBStoragerMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockDBStorager)(nil).Close))
}

// DeleteURLList mocks base method.
func (m *MockDBStorager) DeleteURLList(values []any, placeholders []string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteURLList", values, placeholders)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteURLList indicates an expected call of DeleteURLList.
func (mr *MockDBStoragerMockRecorder) DeleteURLList(values, placeholders any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteURLList", reflect.TypeOf((*MockDBStorager)(nil).DeleteURLList), values, placeholders)
}

// GetStats mocks base method.
func (m *MockDBStorager) GetStats(ctx context.Context) (models.StatsDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStats", ctx)
	ret0, _ := ret[0].(models.StatsDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStats indicates an expected call of GetStats.
func (mr *MockDBStoragerMockRecorder) GetStats(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStats", reflect.TypeOf((*MockDBStorager)(nil).GetStats), ctx)
}

// GetURL mocks base method.
func (m *MockDBStorager) GetURL(ctx context.Context, shortURL string) (models.GetURLDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetURL", ctx, shortURL)
	ret0, _ := ret[0].(models.GetURLDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetURL indicates an expected call of GetURL.
func (mr *MockDBStoragerMockRecorder) GetURL(ctx, shortURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetURL", reflect.TypeOf((*MockDBStorager)(nil).GetURL), ctx, shortURL)
}

// GetURLList mocks base method.
func (m *MockDBStorager) GetURLList(ctx context.Context, userID string) ([]models.BaseURLDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetURLList", ctx, userID)
	ret0, _ := ret[0].([]models.BaseURLDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetURLList indicates an expected call of GetURLList.
func (mr *MockDBStoragerMockRecorder) GetURLList(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetURLList", reflect.TypeOf((*MockDBStorager)(nil).GetURLList), ctx, userID)
}

// Ping mocks base method.
func (m *MockDBStorager) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockDBStoragerMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockDBStorager)(nil).Ping), ctx)
}

// SaveBatchURL mocks base method.
func (m *MockDBStorager) SaveBatchURL(ctx context.Context, entries []repository.URLPair) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveBatchURL", ctx, entries)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveBatchURL indicates an expected call of SaveBatchURL.
func (mr *MockDBStoragerMockRecorder) SaveBatchURL(ctx, entries any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveBatchURL", reflect.TypeOf((*MockDBStorager)(nil).SaveBatchURL), ctx, entries)
}

// SaveURL mocks base method.
func (m *MockDBStorager) SaveURL(ctx context.Context, shortURL, longURLStr, userID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveURL", ctx, shortURL, longURLStr, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveURL indicates an expected call of SaveURL.
func (mr *MockDBStoragerMockRecorder) SaveURL(ctx, shortURL, longURLStr, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveURL", reflect.TypeOf((*MockDBStorager)(nil).SaveURL), ctx, shortURL, longURLStr, userID)
}
