// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: api/url_shortener.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SaveURLRequest represents a request to create a short URL
type SaveURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LongUrl       string                 `protobuf:"bytes,1,opt,name=long_url,json=longUrl,proto3" json:"long_url,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveURLRequest) Reset() {
	*x = SaveURLRequest{}
	mi := &file_api_url_shortener_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveURLRequest) ProtoMessage() {}

func (x *SaveURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_url_shortener_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveURLRequest.ProtoReflect.Descriptor instead.
func (*SaveURLRequest) Descriptor() ([]byte, []int) {
	return file_api_url_shortener_proto_rawDescGZIP(), []int{0}
}

func (x *SaveURLRequest) GetLongUrl() string {
	if x != nil {
		return x.LongUrl
	}
	return ""
}

func (x *SaveURLRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// SaveURLResponse represents a response with a short URL
type SaveURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	IsDouble      bool                   `protobuf:"varint,2,opt,name=is_double,json=isDouble,proto3" json:"is_double,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveURLResponse) Reset() {
	*x = SaveURLResponse{}
	mi := &file_api_url_shortener_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveURLResponse) ProtoMessage() {}

func (x *SaveURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_url_shortener_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveURLResponse.ProtoReflect.Descriptor instead.
func (*SaveURLResponse) Descriptor() ([]byte, []int) {
	return file_api_url_shortener_proto_rawDescGZIP(), []int{1}
}

func (x *SaveURLResponse) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *SaveURLResponse) GetIsDouble() bool {
	if x != nil {
		return x.IsDouble
	}
	return false
}

// GetLongURLRequest represents a request to get original URL
type GetLongURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UrlHash       string                 `protobuf:"bytes,1,opt,name=url_hash,json=urlHash,proto3" json:"url_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLongURLRequest) Reset() {
	*x = GetLongURLRequest{}
	mi := &file_api_url_shortener_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLongURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLongURLRequest) ProtoMessage() {}

func (x *GetLongURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_url_shortener_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLongURLRequest.ProtoReflect.Descriptor instead.
func (*GetLongURLRequest) Descriptor() ([]byte, []int) {
	return file_api_url_shortener_proto_rawDescGZIP(), []int{2}
}

func (x *GetLongURLRequest) GetUrlHash() string {
	if x != nil {
		return x.UrlHash
	}
	return ""
}

// GetLongURLResponse represents a response with original URL
type GetLongURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginalUrl   string                 `protobuf:"bytes,1,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	IsDeleted     bool                   `protobuf:"varint,2,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLongURLResponse) Reset() {
	*x = GetLongURLResponse{}
	mi := &file_api_url_shortener_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLongURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLongURLResponse) ProtoMessage() {}

func (x *GetLongURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_url_shortener_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLongURLResponse.ProtoReflect.Descriptor instead.
func (*GetLongURLResponse) Descriptor() ([]byte, []int) {
	return file_api_url_shortener_proto_rawDescGZIP(), []int{3}
}

func (x *GetLongURLResponse) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

func (x *GetLongURLResponse) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

// APIPrepareShortURLRequest represents an API request to create a short URL
type APIPrepareShortURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LongUrl       string                 `protobuf:"bytes,1,opt,name=long_url,json=longUrl,proto3" json:"long_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIPrepareShortURLRequest) Reset() {
	*x = APIPrepareShortURLRequest{}
	mi := &file_api_url_shortener_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIPrepareShortURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIPrepareShortURLRequest) ProtoMessage() {}

func (x *APIPrepareShortURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_url_shortener_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIPrepareShortURLRequest.ProtoReflect.Descriptor instead.
func (*APIPrepareShortURLRequest) Descriptor() ([]byte, []int) {
	return file_api_url_shortener_proto_rawDescGZIP(), []int{4}
}

func (x *APIPrepareShortURLRequest) GetLongUrl() string {
	if x != nil {
		return x.LongUrl
	}
	return ""
}

// APIPrepareShortURLResponse represents an API response with a short URL
type APIPrepareShortURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	IsDouble      bool                   `protobuf:"varint,2,opt,name=is_double,json=isDouble,proto3" json:"is_double,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIPrepareShortURLResponse) Reset() {
	*x = APIPrepareShortURLResponse{}
	mi := &file_api_url_shortener_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIPrepareShortURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIPrepareShortURLResponse) ProtoMessage() {}

func (x *APIPrepareShortURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_url_shortener_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIPrepareShortURLResponse.ProtoReflect.Descriptor instead.
func (*APIPrepareShortURLResponse) Descriptor() ([]byte, []int) {
	return file_api_url_shortener_proto_rawDescGZIP(), []int{5}
}

func (x *APIPrepareShortURLResponse) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *APIPrepareShortURLResponse) GetIsDouble() bool {
	if x != nil {
		return x.IsDouble
	}
	return false
}

// URLPair represents a URL pair for batch operations
type URLPair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	OriginalUrl   string                 `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	ShortUrl      string                 `protobuf:"bytes,3,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *URLPair) Reset() {
	*x = URLPair{}
	mi := &file_api_url_shortener_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URLPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLPair) ProtoMessage() {}

func (x *URLPair) ProtoReflect() protoreflect.Message {
	mi := &file_api_url_shortener_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URLPair.ProtoReflect.Descriptor instead.
func (*URLPair) Descriptor() ([]byte, []int) {
	return file_api_url_shortener_proto_rawDescGZIP(), []int{6}
}

func (x *URLPair) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *URLPair) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

func (x *URLPair) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

// APIPrepareBatchShortURLRequest represents a batch request to create short URLs
type APIPrepareBatchShortURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          []*URLPair             `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIPrepareBatchShortURLRequest) Reset() {
	*x = APIPrepareBatchShortURLRequest{}
	mi := &file_api_url_shortener_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIPrepareBatchShortURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIPrepareBatchShortURLRequest) ProtoMessage() {}

func (x *APIPrepareBatchShortURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_url_shortener_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIPrepareBatchShortURLRequest.ProtoReflect.Descriptor instead.
func (*APIPrepareBatchShortURLRequest) Descriptor() ([]byte, []int) {
	return file_api_url_shortener_proto_rawDescGZIP(), []int{7}
}

func (x *APIPrepareBatchShortURLRequest) GetUrls() []*URLPair {
	if x != nil {
		return x.Urls
	}
	return nil
}

// APIPrepareBatchShortURLResponse represents a batch response with short URLs
type APIPrepareBatchShortURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          []*URLPair             `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIPrepareBatchShortURLResponse) Reset() {
	*x = APIPrepareBatchShortURLResponse{}
	mi := &file_api_url_shortener_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIPrepareBatchShortURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIPrepareBatchShortURLResponse) ProtoMessage() {}

func (x *APIPrepareBatchShortURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_url_shortener_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIPrepareBatchShortURLResponse.ProtoReflect.Descriptor instead.
func (*APIPrepareBatchShortURLResponse) Descriptor() ([]byte, []int) {
	return file_api_url_shortener_proto_rawDescGZIP(), []int{8}
}

func (x *APIPrepareBatchShortURLResponse) GetUrls() []*URLPair {
	if x != nil {
		return x.Urls
	}
	return nil
}

// BaseURLResponse represents a URL response for user URLs
type BaseURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	OriginalUrl   string                 `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseURLResponse) Reset() {
	*x = BaseURLResponse{}
	mi := &file_api_url_shortener_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseURLResponse) ProtoMessage() {}

func (x *BaseURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_url_shortener_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseURLResponse.ProtoReflect.Descriptor instead.
func (*BaseURLResponse) Descriptor() ([]byte, []int) {
	return file_api_url_shortener_proto_rawDescGZIP(), []int{9}
}

func (x *BaseURLResponse) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *BaseURLResponse) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

// APIGetUserURLsRequest represents a request to get user URLs
type APIGetUserURLsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIGetUserURLsRequest) Reset() {
	*x = APIGetUserURLsRequest{}
	mi := &file_api_url_shortener_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIGetUserURLsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIGetUserURLsRequest) ProtoMessage() {}

func (x *APIGetUserURLsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_url_shortener_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIGetUserURLsRequest.ProtoReflect.Descriptor instead.
func (*APIGetUserURLsRequest) Descriptor() ([]byte, []int) {
	return file_api_url_shortener_proto_rawDescGZIP(), []int{10}
}

func (x *APIGetUserURLsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// APIGetUserURLsResponse represents a response with user URLs
type APIGetUserURLsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          []*BaseURLResponse     `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIGetUserURLsResponse) Reset() {
	*x = APIGetUserURLsResponse{}
	mi := &file_api_url_shortener_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIGetUserURLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIGetUserURLsResponse) ProtoMessage() {}

func (x *APIGetUserURLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_url_shortener_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIGetUserURLsResponse.ProtoReflect.Descriptor instead.
func (*APIGetUserURLsResponse) Descriptor() ([]byte, []int) {
	return file_api_url_shortener_proto_rawDescGZIP(), []int{11}
}

func (x *APIGetUserURLsResponse) GetUrls() []*BaseURLResponse {
	if x != nil {
		return x.Urls
	}
	return nil
}

// APIDeleteUserURLsRequest represents a request to delete user URLs
type APIDeleteUserURLsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UrlHashes     []string               `protobuf:"bytes,2,rep,name=url_hashes,json=urlHashes,proto3" json:"url_hashes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIDeleteUserURLsRequest) Reset() {
	*x = APIDeleteUserURLsRequest{}
	mi := &file_api_url_shortener_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIDeleteUserURLsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIDeleteUserURLsRequest) ProtoMessage() {}

func (x *APIDeleteUserURLsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_url_shortener_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIDeleteUserURLsRequest.ProtoReflect.Descriptor instead.
func (*APIDeleteUserURLsRequest) Descriptor() ([]byte, []int) {
	return file_api_url_shortener_proto_rawDescGZIP(), []int{12}
}

func (x *APIDeleteUserURLsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *APIDeleteUserURLsRequest) GetUrlHashes() []string {
	if x != nil {
		return x.UrlHashes
	}
	return nil
}

// APIDeleteUserURLsResponse represents a response for delete operation
type APIDeleteUserURLsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIDeleteUserURLsResponse) Reset() {
	*x = APIDeleteUserURLsResponse{}
	mi := &file_api_url_shortener_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIDeleteUserURLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIDeleteUserURLsResponse) ProtoMessage() {}

func (x *APIDeleteUserURLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_url_shortener_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIDeleteUserURLsResponse.ProtoReflect.Descriptor instead.
func (*APIDeleteUserURLsResponse) Descriptor() ([]byte, []int) {
	return file_api_url_shortener_proto_rawDescGZIP(), []int{13}
}

func (x *APIDeleteUserURLsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// APIGetStatsRequest represents a request to get application statistics
type APIGetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIGetStatsRequest) Reset() {
	*x = APIGetStatsRequest{}
	mi := &file_api_url_shortener_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIGetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIGetStatsRequest) ProtoMessage() {}

func (x *APIGetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_url_shortener_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIGetStatsRequest.ProtoReflect.Descriptor instead.
func (*APIGetStatsRequest) Descriptor() ([]byte, []int) {
	return file_api_url_shortener_proto_rawDescGZIP(), []int{14}
}

// APIGetStatsResponse represents a response with application statistics
type APIGetStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UrlCount      int64                  `protobuf:"varint,1,opt,name=url_count,json=urlCount,proto3" json:"url_count,omitempty"`
	UserCount     int64                  `protobuf:"varint,2,opt,name=user_count,json=userCount,proto3" json:"user_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIGetStatsResponse) Reset() {
	*x = APIGetStatsResponse{}
	mi := &file_api_url_shortener_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIGetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIGetStatsResponse) ProtoMessage() {}

func (x *APIGetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_url_shortener_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIGetStatsResponse.ProtoReflect.Descriptor instead.
func (*APIGetStatsResponse) Descriptor() ([]byte, []int) {
	return file_api_url_shortener_proto_rawDescGZIP(), []int{15}
}

func (x *APIGetStatsResponse) GetUrlCount() int64 {
	if x != nil {
		return x.UrlCount
	}
	return 0
}

func (x *APIGetStatsResponse) GetUserCount() int64 {
	if x != nil {
		return x.UserCount
	}
	return 0
}

// PingDBRequest represents a request to ping database
type PingDBRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingDBRequest) Reset() {
	*x = PingDBRequest{}
	mi := &file_api_url_shortener_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingDBRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingDBRequest) ProtoMessage() {}

func (x *PingDBRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_url_shortener_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingDBRequest.ProtoReflect.Descriptor instead.
func (*PingDBRequest) Descriptor() ([]byte, []int) {
	return file_api_url_shortener_proto_rawDescGZIP(), []int{16}
}

// PingDBResponse represents a response for database ping
type PingDBResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingDBResponse) Reset() {
	*x = PingDBResponse{}
	mi := &file_api_url_shortener_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingDBResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingDBResponse) ProtoMessage() {}

func (x *PingDBResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_url_shortener_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingDBResponse.ProtoReflect.Descriptor instead.
func (*PingDBResponse) Descriptor() ([]byte, []int) {
	return file_api_url_shortener_proto_rawDescGZIP(), []int{17}
}

func (x *PingDBResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_api_url_shortener_proto protoreflect.FileDescriptor

const file_api_url_shortener_proto_rawDesc = "" +
	"\n" +
	"\x17api/url_shortener.proto\x12\x03api\"D\n" +
	"\x0eSaveURLRequest\x12\x19\n" +
	"\blong_url\x18\x01 \x01(\tR\alongUrl\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"K\n" +
	"\x0fSaveURLResponse\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\x12\x1b\n" +
	"\tis_double\x18\x02 \x01(\bR\bisDouble\".\n" +
	"\x11GetLongURLRequest\x12\x19\n" +
	"\burl_hash\x18\x01 \x01(\tR\aurlHash\"V\n" +
	"\x12GetLongURLResponse\x12!\n" +
	"\foriginal_url\x18\x01 \x01(\tR\voriginalUrl\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\x02 \x01(\bR\tisDeleted\"6\n" +
	"\x19APIPrepareShortURLRequest\x12\x19\n" +
	"\blong_url\x18\x01 \x01(\tR\alongUrl\"V\n" +
	"\x1aAPIPrepareShortURLResponse\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\x12\x1b\n" +
	"\tis_double\x18\x02 \x01(\bR\bisDouble\"p\n" +
	"\aURLPair\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl\x12\x1b\n" +
	"\tshort_url\x18\x03 \x01(\tR\bshortUrl\"B\n" +
	"\x1eAPIPrepareBatchShortURLRequest\x12 \n" +
	"\x04urls\x18\x01 \x03(\v2\f.api.URLPairR\x04urls\"C\n" +
	"\x1fAPIPrepareBatchShortURLResponse\x12 \n" +
	"\x04urls\x18\x01 \x03(\v2\f.api.URLPairR\x04urls\"Q\n" +
	"\x0fBaseURLResponse\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl\"0\n" +
	"\x15APIGetUserURLsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"B\n" +
	"\x16APIGetUserURLsResponse\x12(\n" +
	"\x04urls\x18\x01 \x03(\v2\x14.api.BaseURLResponseR\x04urls\"R\n" +
	"\x18APIDeleteUserURLsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"url_hashes\x18\x02 \x03(\tR\turlHashes\"5\n" +
	"\x19APIDeleteUserURLsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x14\n" +
	"\x12APIGetStatsRequest\"Q\n" +
	"\x13APIGetStatsResponse\x12\x1b\n" +
	"\turl_count\x18\x01 \x01(\x03R\burlCount\x12\x1d\n" +
	"\n" +
	"user_count\x18\x02 \x01(\x03R\tuserCount\"\x0f\n" +
	"\rPingDBRequest\"*\n" +
	"\x0ePingDBResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xd4\x04\n" +
	"\fURLShortener\x124\n" +
	"\aSaveURL\x12\x13.api.SaveURLRequest\x1a\x14.api.SaveURLResponse\x12=\n" +
	"\n" +
	"GetLongURL\x12\x16.api.GetLongURLRequest\x1a\x17.api.GetLongURLResponse\x12U\n" +
	"\x12APIPrepareShortURL\x12\x1e.api.APIPrepareShortURLRequest\x1a\x1f.api.APIPrepareShortURLResponse\x12d\n" +
	"\x17APIPrepareBatchShortURL\x12#.api.APIPrepareBatchShortURLRequest\x1a$.api.APIPrepareBatchShortURLResponse\x12I\n" +
	"\x0eAPIGetUserURLs\x12\x1a.api.APIGetUserURLsRequest\x1a\x1b.api.APIGetUserURLsResponse\x12R\n" +
	"\x11APIDeleteUserURLs\x12\x1d.api.APIDeleteUserURLsRequest\x1a\x1e.api.APIDeleteUserURLsResponse\x12@\n" +
	"\vAPIGetStats\x12\x17.api.APIGetStatsRequest\x1a\x18.api.APIGetStatsResponse\x121\n" +
	"\x06PingDB\x12\x12.api.PingDBRequest\x1a\x13.api.PingDBResponseB'Z%github.com/stlesnik/url_shortener/apib\x06proto3"

var (
	file_api_url_shortener_proto_rawDescOnce sync.Once
	file_api_url_shortener_proto_rawDescData []byte
)

func file_api_url_shortener_proto_rawDescGZIP() []byte {
	file_api_url_shortener_proto_rawDescOnce.Do(func() {
		file_api_url_shortener_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_url_shortener_proto_rawDesc), len(file_api_url_shortener_proto_rawDesc)))
	})
	return file_api_url_shortener_proto_rawDescData
}

var file_api_url_shortener_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_api_url_shortener_proto_goTypes = []any{
	(*SaveURLRequest)(nil),                  // 0: api.SaveURLRequest
	(*SaveURLResponse)(nil),                 // 1: api.SaveURLResponse
	(*GetLongURLRequest)(nil),               // 2: api.GetLongURLRequest
	(*GetLongURLResponse)(nil),              // 3: api.GetLongURLResponse
	(*APIPrepareShortURLRequest)(nil),       // 4: api.APIPrepareShortURLRequest
	(*APIPrepareShortURLResponse)(nil),      // 5: api.APIPrepareShortURLResponse
	(*URLPair)(nil),                         // 6: api.URLPair
	(*APIPrepareBatchShortURLRequest)(nil),  // 7: api.APIPrepareBatchShortURLRequest
	(*APIPrepareBatchShortURLResponse)(nil), // 8: api.APIPrepareBatchShortURLResponse
	(*BaseURLResponse)(nil),                 // 9: api.BaseURLResponse
	(*APIGetUserURLsRequest)(nil),           // 10: api.APIGetUserURLsRequest
	(*APIGetUserURLsResponse)(nil),          // 11: api.APIGetUserURLsResponse
	(*APIDeleteUserURLsRequest)(nil),        // 12: api.APIDeleteUserURLsRequest
	(*APIDeleteUserURLsResponse)(nil),       // 13: api.APIDeleteUserURLsResponse
	(*APIGetStatsRequest)(nil),              // 14: api.APIGetStatsRequest
	(*APIGetStatsResponse)(nil),             // 15: api.APIGetStatsResponse
	(*PingDBRequest)(nil),                   // 16: api.PingDBRequest
	(*PingDBResponse)(nil),                  // 17: api.PingDBResponse
}
var file_api_url_shortener_proto_depIdxs = []int32{
	6,  // 0: api.APIPrepareBatchShortURLRequest.urls:type_name -> api.URLPair
	6,  // 1: api.APIPrepareBatchShortURLResponse.urls:type_name -> api.URLPair
	9,  // 2: api.APIGetUserURLsResponse.urls:type_name -> api.BaseURLResponse
	0,  // 3: api.URLShortener.SaveURL:input_type -> api.SaveURLRequest
	2,  // 4: api.URLShortener.GetLongURL:input_type -> api.GetLongURLRequest
	4,  // 5: api.URLShortener.APIPrepareShortURL:input_type -> api.APIPrepareShortURLRequest
	7,  // 6: api.URLShortener.APIPrepareBatchShortURL:input_type -> api.APIPrepareBatchShortURLRequest
	10, // 7: api.URLShortener.APIGetUserURLs:input_type -> api.APIGetUserURLsRequest
	12, // 8: api.URLShortener.APIDeleteUserURLs:input_type -> api.APIDeleteUserURLsRequest
	14, // 9: api.URLShortener.APIGetStats:input_type -> api.APIGetStatsRequest
	16, // 10: api.URLShortener.PingDB:input_type -> api.PingDBRequest
	1,  // 11: api.URLShortener.SaveURL:output_type -> api.SaveURLResponse
	3,  // 12: api.URLShortener.GetLongURL:output_type -> api.GetLongURLResponse
	5,  // 13: api.URLShortener.APIPrepareShortURL:output_type -> api.APIPrepareShortURLResponse
	8,  // 14: api.URLShortener.APIPrepareBatchShortURL:output_type -> api.APIPrepareBatchShortURLResponse
	11, // 15: api.URLShortener.APIGetUserURLs:output_type -> api.APIGetUserURLsResponse
	13, // 16: api.URLShortener.APIDeleteUserURLs:output_type -> api.APIDeleteUserURLsResponse
	15, // 17: api.URLShortener.APIGetStats:output_type -> api.APIGetStatsResponse
	17, // 18: api.URLShortener.PingDB:output_type -> api.PingDBResponse
	11, // [11:19] is the sub-list for method output_type
	3,  // [3:11] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_api_url_shortener_proto_init() }
func file_api_url_shortener_proto_init() {
	if File_api_url_shortener_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_url_shortener_proto_rawDesc), len(file_api_url_shortener_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_url_shortener_proto_goTypes,
		DependencyIndexes: file_api_url_shortener_proto_depIdxs,
		MessageInfos:      file_api_url_shortener_proto_msgTypes,
	}.Build()
	File_api_url_shortener_proto = out.File
	file_api_url_shortener_proto_goTypes = nil
	file_api_url_shortener_proto_depIdxs = nil
}
