// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: api/url_shortener.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	URLShortener_SaveURL_FullMethodName                 = "/api.URLShortener/SaveURL"
	URLShortener_GetLongURL_FullMethodName              = "/api.URLShortener/GetLongURL"
	URLShortener_APIPrepareShortURL_FullMethodName      = "/api.URLShortener/APIPrepareShortURL"
	URLShortener_APIPrepareBatchShortURL_FullMethodName = "/api.URLShortener/APIPrepareBatchShortURL"
	URLShortener_APIGetUserURLs_FullMethodName          = "/api.URLShortener/APIGetUserURLs"
	URLShortener_APIDeleteUserURLs_FullMethodName       = "/api.URLShortener/APIDeleteUserURLs"
	URLShortener_APIGetStats_FullMethodName             = "/api.URLShortener/APIGetStats"
	URLShortener_PingDB_FullMethodName                  = "/api.URLShortener/PingDB"
)

// URLShortenerClient is the client API for URLShortener service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// URL Shortener Service
type URLShortenerClient interface {
	// SaveURL handles POST requests to save a new URL and return its shortened version.
	SaveURL(ctx context.Context, in *SaveURLRequest, opts ...grpc.CallOption) (*SaveURLResponse, error)
	// GetLongURL handles GET requests to retrieve the original URL from repository by its short hash.
	GetLongURL(ctx context.Context, in *GetLongURLRequest, opts ...grpc.CallOption) (*GetLongURLResponse, error)
	// APIPrepareShortURL handles API requests to shorten a URL and returns the result in JSON.
	APIPrepareShortURL(ctx context.Context, in *APIPrepareShortURLRequest, opts ...grpc.CallOption) (*APIPrepareShortURLResponse, error)
	// APIPrepareBatchShortURL handles API requests to shorten a batch of URLs and returns the results in JSON.
	APIPrepareBatchShortURL(ctx context.Context, in *APIPrepareBatchShortURLRequest, opts ...grpc.CallOption) (*APIPrepareBatchShortURLResponse, error)
	// APIGetUserURLs handles API requests to get all URLs for a user from repository.
	APIGetUserURLs(ctx context.Context, in *APIGetUserURLsRequest, opts ...grpc.CallOption) (*APIGetUserURLsResponse, error)
	// APIDeleteUserURLs handles API requests to delete a batch of user URLs asynchronously.
	APIDeleteUserURLs(ctx context.Context, in *APIDeleteUserURLsRequest, opts ...grpc.CallOption) (*APIDeleteUserURLsResponse, error)
	// APIGetStats handles GET requests from trusted subnet for app stats
	APIGetStats(ctx context.Context, in *APIGetStatsRequest, opts ...grpc.CallOption) (*APIGetStatsResponse, error)
	// PingDB handles health check requests to verify database connectivity.
	PingDB(ctx context.Context, in *PingDBRequest, opts ...grpc.CallOption) (*PingDBResponse, error)
}

type uRLShortenerClient struct {
	cc grpc.ClientConnInterface
}

func NewURLShortenerClient(cc grpc.ClientConnInterface) URLShortenerClient {
	return &uRLShortenerClient{cc}
}

func (c *uRLShortenerClient) SaveURL(ctx context.Context, in *SaveURLRequest, opts ...grpc.CallOption) (*SaveURLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveURLResponse)
	err := c.cc.Invoke(ctx, URLShortener_SaveURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uRLShortenerClient) GetLongURL(ctx context.Context, in *GetLongURLRequest, opts ...grpc.CallOption) (*GetLongURLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLongURLResponse)
	err := c.cc.Invoke(ctx, URLShortener_GetLongURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uRLShortenerClient) APIPrepareShortURL(ctx context.Context, in *APIPrepareShortURLRequest, opts ...grpc.CallOption) (*APIPrepareShortURLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(APIPrepareShortURLResponse)
	err := c.cc.Invoke(ctx, URLShortener_APIPrepareShortURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uRLShortenerClient) APIPrepareBatchShortURL(ctx context.Context, in *APIPrepareBatchShortURLRequest, opts ...grpc.CallOption) (*APIPrepareBatchShortURLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(APIPrepareBatchShortURLResponse)
	err := c.cc.Invoke(ctx, URLShortener_APIPrepareBatchShortURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uRLShortenerClient) APIGetUserURLs(ctx context.Context, in *APIGetUserURLsRequest, opts ...grpc.CallOption) (*APIGetUserURLsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(APIGetUserURLsResponse)
	err := c.cc.Invoke(ctx, URLShortener_APIGetUserURLs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uRLShortenerClient) APIDeleteUserURLs(ctx context.Context, in *APIDeleteUserURLsRequest, opts ...grpc.CallOption) (*APIDeleteUserURLsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(APIDeleteUserURLsResponse)
	err := c.cc.Invoke(ctx, URLShortener_APIDeleteUserURLs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uRLShortenerClient) APIGetStats(ctx context.Context, in *APIGetStatsRequest, opts ...grpc.CallOption) (*APIGetStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(APIGetStatsResponse)
	err := c.cc.Invoke(ctx, URLShortener_APIGetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uRLShortenerClient) PingDB(ctx context.Context, in *PingDBRequest, opts ...grpc.CallOption) (*PingDBResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingDBResponse)
	err := c.cc.Invoke(ctx, URLShortener_PingDB_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// URLShortenerServer is the server API for URLShortener service.
// All implementations must embed UnimplementedURLShortenerServer
// for forward compatibility.
//
// URL Shortener Service
type URLShortenerServer interface {
	// SaveURL handles POST requests to save a new URL and return its shortened version.
	SaveURL(context.Context, *SaveURLRequest) (*SaveURLResponse, error)
	// GetLongURL handles GET requests to retrieve the original URL from repository by its short hash.
	GetLongURL(context.Context, *GetLongURLRequest) (*GetLongURLResponse, error)
	// APIPrepareShortURL handles API requests to shorten a URL and returns the result in JSON.
	APIPrepareShortURL(context.Context, *APIPrepareShortURLRequest) (*APIPrepareShortURLResponse, error)
	// APIPrepareBatchShortURL handles API requests to shorten a batch of URLs and returns the results in JSON.
	APIPrepareBatchShortURL(context.Context, *APIPrepareBatchShortURLRequest) (*APIPrepareBatchShortURLResponse, error)
	// APIGetUserURLs handles API requests to get all URLs for a user from repository.
	APIGetUserURLs(context.Context, *APIGetUserURLsRequest) (*APIGetUserURLsResponse, error)
	// APIDeleteUserURLs handles API requests to delete a batch of user URLs asynchronously.
	APIDeleteUserURLs(context.Context, *APIDeleteUserURLsRequest) (*APIDeleteUserURLsResponse, error)
	// APIGetStats handles GET requests from trusted subnet for app stats
	APIGetStats(context.Context, *APIGetStatsRequest) (*APIGetStatsResponse, error)
	// PingDB handles health check requests to verify database connectivity.
	PingDB(context.Context, *PingDBRequest) (*PingDBResponse, error)
	mustEmbedUnimplementedURLShortenerServer()
}

// UnimplementedURLShortenerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedURLShortenerServer struct{}

func (UnimplementedURLShortenerServer) SaveURL(context.Context, *SaveURLRequest) (*SaveURLResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveURL not implemented")
}
func (UnimplementedURLShortenerServer) GetLongURL(context.Context, *GetLongURLRequest) (*GetLongURLResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLongURL not implemented")
}
func (UnimplementedURLShortenerServer) APIPrepareShortURL(context.Context, *APIPrepareShortURLRequest) (*APIPrepareShortURLResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method APIPrepareShortURL not implemented")
}
func (UnimplementedURLShortenerServer) APIPrepareBatchShortURL(context.Context, *APIPrepareBatchShortURLRequest) (*APIPrepareBatchShortURLResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method APIPrepareBatchShortURL not implemented")
}
func (UnimplementedURLShortenerServer) APIGetUserURLs(context.Context, *APIGetUserURLsRequest) (*APIGetUserURLsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method APIGetUserURLs not implemented")
}
func (UnimplementedURLShortenerServer) APIDeleteUserURLs(context.Context, *APIDeleteUserURLsRequest) (*APIDeleteUserURLsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method APIDeleteUserURLs not implemented")
}
func (UnimplementedURLShortenerServer) APIGetStats(context.Context, *APIGetStatsRequest) (*APIGetStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method APIGetStats not implemented")
}
func (UnimplementedURLShortenerServer) PingDB(context.Context, *PingDBRequest) (*PingDBResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PingDB not implemented")
}
func (UnimplementedURLShortenerServer) mustEmbedUnimplementedURLShortenerServer() {}
func (UnimplementedURLShortenerServer) testEmbeddedByValue()                      {}

// UnsafeURLShortenerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to URLShortenerServer will
// result in compilation errors.
type UnsafeURLShortenerServer interface {
	mustEmbedUnimplementedURLShortenerServer()
}

func RegisterURLShortenerServer(s grpc.ServiceRegistrar, srv URLShortenerServer) {
	// If the following call pancis, it indicates UnimplementedURLShortenerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&URLShortener_ServiceDesc, srv)
}

func _URLShortener_SaveURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(URLShortenerServer).SaveURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: URLShortener_SaveURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(URLShortenerServer).SaveURL(ctx, req.(*SaveURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _URLShortener_GetLongURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLongURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(URLShortenerServer).GetLongURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: URLShortener_GetLongURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(URLShortenerServer).GetLongURL(ctx, req.(*GetLongURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _URLShortener_APIPrepareShortURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(APIPrepareShortURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(URLShortenerServer).APIPrepareShortURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: URLShortener_APIPrepareShortURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(URLShortenerServer).APIPrepareShortURL(ctx, req.(*APIPrepareShortURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _URLShortener_APIPrepareBatchShortURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(APIPrepareBatchShortURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(URLShortenerServer).APIPrepareBatchShortURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: URLShortener_APIPrepareBatchShortURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(URLShortenerServer).APIPrepareBatchShortURL(ctx, req.(*APIPrepareBatchShortURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _URLShortener_APIGetUserURLs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(APIGetUserURLsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(URLShortenerServer).APIGetUserURLs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: URLShortener_APIGetUserURLs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(URLShortenerServer).APIGetUserURLs(ctx, req.(*APIGetUserURLsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _URLShortener_APIDeleteUserURLs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(APIDeleteUserURLsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(URLShortenerServer).APIDeleteUserURLs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: URLShortener_APIDeleteUserURLs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(URLShortenerServer).APIDeleteUserURLs(ctx, req.(*APIDeleteUserURLsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _URLShortener_APIGetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(APIGetStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(URLShortenerServer).APIGetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: URLShortener_APIGetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(URLShortenerServer).APIGetStats(ctx, req.(*APIGetStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _URLShortener_PingDB_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingDBRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(URLShortenerServer).PingDB(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: URLShortener_PingDB_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(URLShortenerServer).PingDB(ctx, req.(*PingDBRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// URLShortener_ServiceDesc is the grpc.ServiceDesc for URLShortener service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var URLShortener_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.URLShortener",
	HandlerType: (*URLShortenerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveURL",
			Handler:    _URLShortener_SaveURL_Handler,
		},
		{
			MethodName: "GetLongURL",
			Handler:    _URLShortener_GetLongURL_Handler,
		},
		{
			MethodName: "APIPrepareShortURL",
			Handler:    _URLShortener_APIPrepareShortURL_Handler,
		},
		{
			MethodName: "APIPrepareBatchShortURL",
			Handler:    _URLShortener_APIPrepareBatchShortURL_Handler,
		},
		{
			MethodName: "APIGetUserURLs",
			Handler:    _URLShortener_APIGetUserURLs_Handler,
		},
		{
			MethodName: "APIDeleteUserURLs",
			Handler:    _URLShortener_APIDeleteUserURLs_Handler,
		},
		{
			MethodName: "APIGetStats",
			Handler:    _URLShortener_APIGetStats_Handler,
		},
		{
			MethodName: "PingDB",
			Handler:    _URLShortener_PingDB_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/url_shortener.proto",
}
